/**
 * modules/connect/ServerConnectScreen.tsx
 *
 * The pre-login flow from the spec:
 *   Connect to Server → Find LAN Server / Scan QR / Enter IP → Select Server
 *     → Pair This Device → (hands off to the normal LoginPage)
 *
 * Reuses, rather than duplicates:
 *   - devicesAPI.pairClaim (services/api.ts) — the exact same backend route
 *     (`POST /devices/pair/claim`) the already-logged-in Devices & Sync
 *     "Connect via QR" flow uses.
 *   - getDeviceId() (offline/idGen.ts) — the same persisted per-install
 *     device id every other device-aware feature in this app already uses.
 *   - ProductScanModal — the same camera/QR-scanning component Devices &
 *     Sync already uses for "Connect via QR", so this pass adds no new
 *     scanning dependency.
 *   - services/discovery.ts + config/serverConnection.ts for everything
 *     LAN-connection-specific that genuinely doesn't exist yet.
 *
 * A QR generated by Settings → Devices & Sync → "Add Device" already
 * encodes exactly `{ token, apiBaseUrl }` (see DevicesSyncSection.tsx) —
 * scanning it here both selects the server AND supplies the pairing token
 * in one step. Reaching this screen via LAN discovery or manual IP entry
 * has no token, so pairing is a second, explicit step: the code is also
 * shown as plain text next to that QR for exactly this case (see the
 * small addition in DevicesSyncSection.tsx).
 */
import { useEffect, useRef, useState } from 'react'
import { Capacitor } from '@capacitor/core'
import { Wifi, QrCode, Keyboard, CheckCircle2, ServerCog, ArrowLeft } from 'lucide-react'
import { Card, Button, Input, Alert, Spinner } from '@/components/ui'
import ProductScanModal from '@/components/scanner/ProductScanModal'
import { devicesAPI } from '@/services/api'
import { getDeviceId } from '@/offline/idGen'
import { discoverLanServers, probeServerUrl, type DiscoveredServer } from '@/services/discovery'
import { saveServer, normalizeServerInput } from '@/config/serverConnection'

const APP_VERSION = '2.0.0'
function platformName(): string {
  try { return Capacitor.getPlatform() } catch { return 'web' }
}

type Step = 'choose' | 'discovering' | 'manual' | 'pairing-code' | 'pairing' | 'done'

interface PendingServer {
  baseUrl: string
  name: string
  token?: string // present only when the server was selected via QR
}

export default function ServerConnectScreen({ onConnected }: { onConnected: () => void }) {
  const [step, setStep] = useState<Step>('choose')
  const [servers, setServers] = useState<DiscoveredServer[]>([])
  const [scanOpen, setScanOpen] = useState(false)
  const [manualValue, setManualValue] = useState('')
  const [manualError, setManualError] = useState<string | null>(null)
  const [manualBusy, setManualBusy] = useState(false)
  const [pending, setPending] = useState<PendingServer | null>(null)
  const [pairCode, setPairCode] = useState('')
  const [pairError, setPairError] = useState<string | null>(null)
  const [pairBusy, setPairBusy] = useState(false)
  const sweepAbort = useRef<AbortController | null>(null)

  useEffect(() => () => sweepAbort.current?.abort(), [])

  function startDiscovery() {
    setServers([])
    setStep('discovering')
    sweepAbort.current?.abort()
    const controller = new AbortController()
    sweepAbort.current = controller
    discoverLanServers((s) => setServers((prev) => [...prev, s]), controller.signal)
  }

  function stopDiscovery() {
    sweepAbort.current?.abort()
  }

  function selectDiscovered(s: DiscoveredServer) {
    stopDiscovery()
    setPending({ baseUrl: s.baseUrl, name: s.name })
    setPairError(null)
    setPairCode('')
    setStep('pairing-code')
  }

  async function handleScannedCode(raw: string) {
    setScanOpen(false)
    let parsed: { token?: string; apiBaseUrl?: string }
    try { parsed = JSON.parse(raw) } catch { setManualError('That QR code isn\u2019t a Byapar pairing code.'); setStep('manual'); return }
    if (!parsed.token || !parsed.apiBaseUrl) { setManualError('That QR code isn\u2019t a Byapar pairing code.'); setStep('manual'); return }

    setManualBusy(true)
    setManualError(null)
    const found = await probeServerUrl(parsed.apiBaseUrl)
    setManualBusy(false)
    if (!found) {
      setManualError('Could not reach that server. Make sure this device is on the same network.')
      setStep('manual')
      return
    }
    // QR already carried a token — skip straight to pairing, no manual code entry needed.
    setPending({ baseUrl: found.baseUrl, name: found.name, token: parsed.token })
    void completePairing({ baseUrl: found.baseUrl, name: found.name, token: parsed.token })
  }

  async function handleManualConnect() {
    const normalized = normalizeServerInput(manualValue)
    if (!normalized) { setManualError('Enter a valid address, e.g. 192.168.1.7:5000'); return }
    setManualBusy(true)
    setManualError(null)
    const found = await probeServerUrl(normalized)
    setManualBusy(false)
    if (!found) {
      setManualError('No Byapar server found at that address.')
      return
    }
    setPending({ baseUrl: found.baseUrl, name: found.name })
    setPairError(null)
    setPairCode('')
    setStep('pairing-code')
  }

  async function completePairing(target: PendingServer) {
    setStep('pairing')
    setPairBusy(true)
    setPairError(null)
    try {
      const deviceName = `${platformName() === 'web' ? 'Browser' : platformName()} device`
      const res = await devicesAPI.pairClaim({
        token: target.token!,
        device_id: getDeviceId(),
        device_name: deviceName,
        platform: platformName(),
        app_version: APP_VERSION,
      })
      saveServer({ baseUrl: target.baseUrl, name: target.name, connectedAt: new Date().toISOString() })
      void res // device_secret, if returned, is a nice-to-have hardening not required for this flow to work
      setStep('done')
      setTimeout(onConnected, 600)
    } catch (e: any) {
      setPairError(e?.message || 'Pairing failed. Check the code and try again.')
      setStep('pairing-code')
    } finally {
      setPairBusy(false)
    }
  }

  function submitPairCode() {
    if (!pending || !pairCode.trim()) return
    void completePairing({ ...pending, token: pairCode.trim() })
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-[var(--surface-2)] p-4">
      <div className="w-full max-w-md">
        <div className="text-center mb-6">
          <div className="inline-flex items-center justify-center w-12 h-12 rounded-2xl bg-brand/10 text-brand mb-3">
            <ServerCog size={24} />
          </div>
          <h1 className="text-lg font-bold text-[var(--text)]">Connect to Server</h1>
          <p className="text-sm text-[var(--text-4)] mt-1">
            This device needs to connect to your company's Byapar server before you can log in.
          </p>
        </div>

        <Card>
          {step === 'choose' && (
            <div className="flex flex-col gap-2.5">
              <Button variant="primary" size="lg" className="justify-start" onClick={startDiscovery}>
                <Wifi size={16} /> Find LAN Server
              </Button>
              <Button variant="secondary" size="lg" className="justify-start" onClick={() => setScanOpen(true)}>
                <QrCode size={16} /> Scan QR Code
              </Button>
              <Button variant="secondary" size="lg" className="justify-start" onClick={() => { setManualError(null); setStep('manual') }}>
                <Keyboard size={16} /> Enter Server Address
              </Button>
            </div>
          )}

          {step === 'discovering' && (
            <div className="flex flex-col gap-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2 text-sm text-[var(--text-2)]">
                  <Spinner size={14} /> Searching your network…
                </div>
                <Button variant="ghost" size="sm" onClick={() => { stopDiscovery(); setStep('choose') }}>
                  <ArrowLeft size={13} /> Back
                </Button>
              </div>

              {servers.length === 0 ? (
                <p className="text-xs text-[var(--text-4)] py-4 text-center">
                  No servers found yet — make sure the server PC is on and this device is on the same WiFi.
                </p>
              ) : (
                <div className="flex flex-col gap-2">
                  {servers.map((s) => (
                    <button
                      key={`${s.host}:${s.port}`}
                      onClick={() => selectDiscovered(s)}
                      className="flex items-center justify-between text-left border border-[var(--border)] rounded-lg px-3 py-2.5 hover:border-brand transition-colors"
                    >
                      <div>
                        <div className="text-sm font-semibold text-[var(--text)]">{s.name}</div>
                        <div className="text-xs text-[var(--text-4)]">{s.host}:{s.port}</div>
                      </div>
                      <span className="flex items-center gap-1 text-xs text-green-600">
                        <span className="w-1.5 h-1.5 rounded-full bg-green-500" /> Online
                      </span>
                    </button>
                  ))}
                </div>
              )}

              <div className="flex gap-2 pt-1">
                <Button variant="secondary" size="sm" className="flex-1" onClick={() => setScanOpen(true)}>
                  <QrCode size={13} /> Scan QR instead
                </Button>
                <Button variant="secondary" size="sm" className="flex-1" onClick={() => { stopDiscovery(); setManualError(null); setStep('manual') }}>
                  <Keyboard size={13} /> Enter IP instead
                </Button>
              </div>
            </div>
          )}

          {step === 'manual' && (
            <div className="flex flex-col gap-3">
              <Button variant="ghost" size="sm" className="self-start" onClick={() => setStep('choose')}>
                <ArrowLeft size={13} /> Back
              </Button>
              <Input
                label="Server Address"
                placeholder="192.168.1.7:5000"
                value={manualValue}
                onChange={(e) => setManualValue(e.target.value)}
                autoFocus
              />
              {manualError && <Alert type="danger" message={manualError} onClose={() => setManualError(null)} />}
              <Button variant="primary" onClick={handleManualConnect} loading={manualBusy}>
                Connect
              </Button>
            </div>
          )}

          {step === 'pairing-code' && pending && (
            <div className="flex flex-col gap-3">
              <Button variant="ghost" size="sm" className="self-start" onClick={() => { setPending(null); setStep('choose') }}>
                <ArrowLeft size={13} /> Back
              </Button>
              <div className="text-sm text-[var(--text-2)]">
                Connected to <span className="font-semibold text-[var(--text)]">{pending.name}</span>.
                Now enter the pairing code shown on an already set-up device
                (Settings → Devices & Sync → Add Device).
              </div>
              <Input
                label="Pairing Code"
                placeholder="Paste the code here"
                value={pairCode}
                onChange={(e) => setPairCode(e.target.value)}
                autoFocus
              />
              {pairError && <Alert type="danger" message={pairError} onClose={() => setPairError(null)} />}
              <Button variant="primary" onClick={submitPairCode} loading={pairBusy} disabled={!pairCode.trim()}>
                Pair This Device
              </Button>
            </div>
          )}

          {step === 'pairing' && (
            <div className="flex flex-col items-center gap-3 py-6">
              <Spinner size={22} />
              <p className="text-sm text-[var(--text-3)]">Pairing this device…</p>
            </div>
          )}

          {step === 'done' && (
            <div className="flex flex-col items-center gap-3 py-6">
              <CheckCircle2 size={28} className="text-green-600" />
              <p className="text-sm font-semibold text-[var(--text)]">Device paired</p>
              <p className="text-xs text-[var(--text-4)]">Continuing to login…</p>
            </div>
          )}
        </Card>

        <p className="text-center text-xs text-[var(--text-4)] mt-4">
          Being on the same WiFi only finds the server — signing in still needs your real
          account, and this device only gains access once an admin's pairing code confirms it.
        </p>
      </div>

      <ProductScanModal
        open={scanOpen}
        onClose={() => setScanOpen(false)}
        onBarcode={(code) => { void handleScannedCode(code) }}
      />
    </div>
  )
}
